### ISSUE TITLE
WIP: Improve usability

### ISSUE THREAD

**Issue by jasonncleveland** [CodingGrounds/ManageMyAssets#24]
General Bugs
- [ ] Provide an explanation as to why location permissions are required (Tell them that it is used to display and follow their location on the map

Main Activity Bugs
- [ ] Sometimes I cant get the Image java.io.FileNotFoundException

AddAssetActivity Bugs
- [x] Make it more apparent that the user can manually enter coordinates and not just use their current location
- [x] Allow user to enter multiple assets at a time instead of immediately taking them to the map view after an asset is saved
- [x] Make AddAssetActivity scroll whenever a long description or note is added
- [x] Add padding around text boxes in AddAssetActivity
- [x] Fabs should not be green
- [x] Enter address cancel and ok is green
- [x] Overlap on add button when adding lat and long manually  
- [x] Lat and lng are the wrong way around
- [x] Trim textview lng and lat
- [x] Remove camera fab and make the image clickable
- [x] The image needs a new placeholder
- [x] Pressing the button to view on map works, but when the user navigates back using the device back button and attempts to hit the button again, it errors out saying "task cannot be executed again"
- [ ] Have photo be appropriately rotated in AddAssetActivity when a photo is taken
- [ ] Multiple fabs should go sideways
- [ ] Cant find location toast is popping up out of sight bc of keyboard
- [ ] Add location by address sometimes fucks up
- [ ] Little fabs don't close unless the large fab is pressed. Should close when they lose focus

Map Activity Bugs
- [x] Center the map on the user's current location after permission to use location has been granted
- [x] Map to Asset adds a new asset in. Should be in fixed in other branches
- [x] Edit flow is wrong, makes me add it again weird
- [x]  onCreate makes a non-asynchronous call to the database when it should be called asynchronously
- [x] Not able to click on map to add an asset after opening and closing a marker. Works fine before a marker is clicked

- [ ] Add a fab in the MapActivity with a plus to take the user to the add screen

**Comment by ShutUpChips15** [comment]
Major Bug: Runtime Slowing the app down.

03-28 22:42:17.390 27436-27436/ca.unb.mobiledev.managemyassets W/LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
                                                                                java.lang.RuntimeException
                                                                                    at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1850)
                                                                                    at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1967)
                                                                                    at android.graphics.drawable.RippleDrawable$RippleState.<init>(RippleDrawable.java:997)
                                                                                    at android.graphics.drawable.RippleDrawable.createConstantState(RippleDrawable.java:988)
                                                                                    at android.graphics.drawable.RippleDrawable.createConstantState(RippleDrawable.java:986)
                                                                                    at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1774)
                                                                                    at android.graphics.drawable.RippleDrawable.mutate(RippleDrawable.java:974)
                                                                                    at android.view.View.applyBackgroundTint(View.java:20601)
                                                                                    at android.view.View.setBackgroundDrawable(View.java:20472)
                                                                                    at android.support.design.widget.FloatingActionButton.access$001(FloatingActionButton.java:68)
                                                                                    at android.support.design.widget.FloatingActionButton$ShadowDelegateImpl.setBackgroundDrawable(FloatingActionButton.java:824)
                                                                                    at android.support.design.widget.FloatingActionButtonLollipop.setBackgroundDrawable(FloatingActionButtonLollipop.java:73)
                                                                                    at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:179)
                                                                                    at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:151)
                                                                                    at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                    at ca.unb.mobiledev.managemyassets.MapActivity.onCreate(MapActivity.java:60)
                                                                                    at android.app.Activity.performCreate(Activity.java:6999)
                                                                                    at android.app.Activity.performCreate(Activity.java:6990)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                    at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-28 22:42:17.411 27436-27436/ca.unb.mobiledev.managemyassets W/LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
                                                                                java.lang.RuntimeException
                                                                                    at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1850)
                                                                                    at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1967)
                                                                                    at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:168)
                                                                                    at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1774)
                                                                                    at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1780)
                                                                                    at android.graphics.drawable.RippleDrawable.mutate(RippleDrawable.java:974)
                                                                                    at android.view.View.applyBackgroundTint(View.java:20601)
                                                                                    at android.view.View.setBackgroundDrawable(View.java:20472)
                                                                                    at android.support.design.widget.FloatingActionButton.access$001(FloatingActionButton.java:68)
                                                                                    at android.support.design.widget.FloatingActionButton$ShadowDelegateImpl.setBackgroundDrawable(FloatingActionButton.java:824)
                                                                                    at android.support.design.widget.FloatingActionButtonLollipop.setBackgroundDrawable(FloatingActionButtonLollipop.java:73)
                                                                                    at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:179)
                                                                                    at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:151)
                                                                                    at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                    at ca.unb.mobiledev.managemyassets.MapActivity.onCreate(MapActivity.java:60)
                                                                                    at android.app.Activity.performCreate(Activity.java:6999)
                                                                                    at android.app.Activity.performCreate(Activity.java:6990)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                    at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-28 22:42:17.496 27436-27436/ca.unb.mobiledev.managemyassets I/Choreographer: Skipped 140 frames!  The application may be doing too much work on its main thread.
